name: Akamai Cache Purge Plugin
id: AkamaiCachePurge
author_link: http://www.treehugger.com
author_name: Ben Boyd
description: This plugin initiates purge requests for individual entries upon republishing.
version: 0.1
callbacks:
	MT::App::CMS::cms_post_save.entry: $AkamaiCachePurge::AkamaiCachePurge::Plugin::purge_url
settings:
	akamai_username:
		Default: ''
		Scope: system
	akamai_password:
		Default: ''
		Scope: system
	notification_email:
		Default: ''
		Scope: system
system_config_template: config_template.tmpl




